import { FC, ReactNode } from 'react'

import type { Metadata } from 'next'

import Header from './Header'
import Footer from './Footer'

interface LayoutI {
  children: ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Layout: FC<LayoutI> = ({ children }) => {
  return (
    <div className="bg-[#0E0E12]">
      <Header />
      <main>
        <section>{children}</section>
      </main>
      <Footer />
    </div>
  )
}

export default Layout
