import { FC, ReactNode } from "react";
import { Lexend } from "next/font/google";

import { usePathname } from "next/navigation";
import type { Metadata } from "next";

import styled from "styled-components";

import Header from "./Header";
import Footer from "./Footer";

interface LayoutI {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lexend = Lexend({ subsets: ["latin"] });

const Layout: FC<LayoutI> = ({ children }) => {
  const pathname = usePathname();

  return (
    <WrapperLayout className={lexend.className}>
      <Header />
      <main>
        <section>{children}</section>
      </main>
      {pathname === "footer" ? <Footer /> : null}
    </WrapperLayout>
  );
};

const WrapperLayout = styled.section`
  background-image: url("/images/layout/bg.png");
  background-size: 100% 100%;
  background-repeat: no-repeat;
  background-position: center center;
`;

export default Layout;
